default: 
circle: 
cdko: 
kirby: 
jieenado: 
splatoon3: 
zonai: 
custom_emoji-ff14_beginner: 
custom_emoji-ff14_returner: 
custom_emoji-ff14_mentor_battle: 
custom_emoji-ff14_mentor_trade: 
custom_emoji-ff14_mentor_pvp: 
custom_emoji-ff14_mentor: 
salmonrunhelp: 
ffxiv: 